blank_issues_enabled: false
contact_links:
  - name: Questões de Segurança e Vulnerabilidades
    url: mailto:seguranca@purelifebrasil.org
    about: Relate vulnerabilidades de segurança de forma confidencial.
